version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    # Layer of protection against supply chain attacks (e.g., Sha1-Hulud) by waiting 7 days
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "npm"
      prefix-development: "npm dev"
      include: "scope"
    groups:
      minor-patch-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    # Layer of protection against supply chain attacks (e.g., Sha1-Hulud) by waiting 7 days
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "github-actions"
      include: "scope"

